import { prisma } from "@/lib/prisma"

interface AwardCategory {
  name: string
  category: string
  icon: string
  description: string
}

const AWARD_CATEGORIES: AwardCategory[] = [
  { name: "Champion", category: "CHAMPION", icon: "Crown", description: "Season winner" },
  { name: "Golden Boot", category: "GOLDEN_BOOT", icon: "Trophy", description: "Most goals scored" },
  { name: "Player of the Season", category: "PLAYER_OF_THE_SEASON", icon: "Star", description: "Best overall player" },
]

export async function generateSeasonAwards(seasonId: string) {
  try {
    const season = await prisma.season.findUnique({
      where: { id: seasonId },
      include: {
        leagueEntries: {
          include: { 
            player: { 
              include: { profile: true } 
            } 
          },
          orderBy: { points: 'desc' }
        }
      }
    })

    if (!season) throw new Error("Season not found")

    const entries = season.leagueEntries
    if (entries.length === 0) {
      return { success: false, message: "No players in season" }
    }

    // Check if awards already exist
    const existingAwards = await prisma.award.count({
      where: { seasonId }
    })

    if (existingAwards > 0) {
      return { success: false, message: "Awards already exist for this season" }
    }

    const awardsToCreate = []

    // 1. Champion: Highest points
    const champion = entries[0]
    if (champion) {
      awardsToCreate.push({
        seasonId,
        name: "Champion",
        category: "CHAMPION",
        icon: "Crown",
        winnerId: champion.playerId,
        description: `Season ${season.name} Champion with ${champion.points} points`,
        isAutoGenerated: true,
        awardedAt: new Date()
      })
    }

    // 2. Golden Boot: Most goals
    const goldenBoot = entries.reduce((a, b) => a.goalsFor > b.goalsFor ? a : b)
    if (goldenBoot && goldenBoot.goalsFor > 0) {
      awardsToCreate.push({
        seasonId,
        name: "Golden Boot",
        category: "GOLDEN_BOOT",
        icon: "Trophy",
        winnerId: goldenBoot.playerId,
        description: `Most goals scored (${goldenBoot.goalsFor}) in ${season.name}`,
        isAutoGenerated: true,
        awardedAt: new Date()
      })
    }

    // 3. Player of the Season: Best overall
    const playerOfTheSeason = entries.reduce((a, b) => {
      const scoreA = a.points + a.goalsFor + a.wins * 2
      const scoreB = b.points + b.goalsFor + b.wins * 2
      return scoreA > scoreB ? a : b
    })
    if (playerOfTheSeason) {
      awardsToCreate.push({
        seasonId,
        name: "Player of the Season",
        category: "PLAYER_OF_THE_SEASON",
        icon: "Star",
        winnerId: playerOfTheSeason.playerId,
        description: `Best overall player in ${season.name}`,
        isAutoGenerated: true,
        awardedAt: new Date()
      })
    }

    // Save awards to database
    const createdAwards = []
    for (const awardData of awardsToCreate) {
      const award = await prisma.award.create({ data: awardData })
      createdAwards.push(award)

      // Also add to Hall of Fame
      const winner = await prisma.user.findUnique({
        where: { id: awardData.winnerId },
        include: { profile: true }
      })

      await prisma.hallOfFame.create({
        data: {
          playerId: awardData.winnerId,
          seasonId: seasonId,
          category: awardData.category,
          reason: `${awardData.name} - ${awardData.description}`,
          imageUrl: winner?.profile?.profilePicture || null,
          inductedAt: new Date()
        }
      })
    }

    return {
      success: true,
      message: `Generated ${createdAwards.length} awards for season ${season.name}`,
      awards: createdAwards
    }
  } catch (error) {
    console.error("Error generating awards:", error)
    throw error
  }
}

export async function deleteSeasonAwards(seasonId: string) {
  try {
    // Delete awards
    await prisma.award.deleteMany({
      where: { seasonId }
    })

    // Delete Hall of Fame entries for this season
    await prisma.hallOfFame.deleteMany({
      where: { seasonId }
    })

    return { success: true, message: "Awards and Hall of Fame entries deleted" }
  } catch (error) {
    console.error("Error deleting awards:", error)
    throw error
  }
}

export async function getAwardCategories() {
  return AWARD_CATEGORIES
}