import { NextResponse } from "next/server"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import { notificationWithEmailService } from "@/lib/services/notificationWithEmail.service"

export async function GET() {
  try {
    const session = await getServerSession(authOptions)
    
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    // Get awards with winner and season info
    const awards = await prisma.award.findMany({
      include: {
        winner: {
          include: { profile: true }
        },
        season: true
      },
      orderBy: { awardedAt: 'desc' }
    })

    return NextResponse.json(awards)
  } catch (error) {
    console.error("Error fetching awards:", error)
    return NextResponse.json([])
  }
}

export async function POST(request: Request) {
  try {
    const session = await getServerSession(authOptions)
    
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }
    
    if (session.user.role !== "ADMIN") {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 })
    }

    const body = await request.json()
    const { seasonId, name, category, icon, winnerId, description, isAutoGenerated } = body

    const award = await prisma.award.create({
      data: {
        seasonId,
        name,
        category: category || "CUSTOM",
        icon: icon || "Award",
        winnerId,
        description: description || "",
        isAutoGenerated: isAutoGenerated || false,
        awardedAt: new Date()
      }
    })

    // ✅ Send email notification to award winner
    if (winnerId) {
      const winner = await prisma.user.findUnique({
        where: { id: winnerId },
        include: { profile: true }
      })

      if (winner) {
        await notificationWithEmailService.sendAwardNotification(winnerId, {
          name: name,
          reason: description || `You've been awarded the ${name} award!`,
          link: `/dashboard/awards`
        })
      }
    }

    return NextResponse.json(award, { status: 201 })
  } catch (error) {
    console.error("Error creating award:", error)
    return NextResponse.json(
      { error: "Failed to create award" },
      { status: 500 }
    )
  }
}

export async function DELETE(request: Request) {
  try {
    const session = await getServerSession(authOptions)
    
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }
    
    if (session.user.role !== "ADMIN") {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 })
    }

    const { searchParams } = new URL(request.url)
    const id = searchParams.get("id")

    if (!id) {
      return NextResponse.json({ error: "Award ID required" }, { status: 400 })
    }

    await prisma.award.delete({
      where: { id }
    })

    return NextResponse.json({ success: true })
  } catch (error) {
    console.error("Error deleting award:", error)
    return NextResponse.json(
      { error: "Failed to delete award" },
      { status: 500 }
    )
  }
}