"use client";

import { memo, useEffect, useMemo, useState, type ReactNode, useCallback } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import {
  Trophy,
  Crown,
  Star,
  Shield,
  Sparkles,
  TrendingUp,
  Target,
  Trash2,
  Calendar,
  Users,
  RefreshCw,
  Award,
  Search,
  Filter,
  Wand2,
  Medal,
  Bot,
  UserRound,
  CheckCircle,
  Loader2,
  ChevronRight,
  X,
} from "lucide-react";
import toast from "react-hot-toast";
import { Skeleton } from "@/components/ui/Skeleton";

interface Award {
  id: string;
  name: string;
  category: string;
  icon: string;
  description: string;
  awardedAt: string;
  isAutoGenerated: boolean;
  winner: {
    name: string;
    profile: { username: string };
  };
  season: {
    name: string;
    id: string;
  };
}

interface Season {
  id: string;
  name: string;
  isActive: boolean;
}

const iconMap: Record<string, ReactNode> = {
  Crown: <Crown className="h-5 w-5 text-yellow-400" />,
  Trophy: <Trophy className="h-5 w-5 text-amber-400" />,
  Shield: <Shield className="h-5 w-5 text-blue-400" />,
  Star: <Star className="h-5 w-5 text-purple-400" />,
  TrendingUp: <TrendingUp className="h-5 w-5 text-green-400" />,
  Sparkles: <Sparkles className="h-5 w-5 text-pink-400" />,
  Target: <Target className="h-5 w-5 text-red-400" />,
  Award: <Award className="h-5 w-5 text-indigo-400" />,
};

/* -------------------------------------------------------------------------- */
/*                           Performance Hooks                                */
/* -------------------------------------------------------------------------- */

// === Mobile Detection Hook ===
function useIsMobile() {
  const [isMobile, setIsMobile] = useState(false);
  
  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);
  
  return isMobile;
}

/* -------------------------------------------------------------------------- */
/*                            Helper Functions                                */
/* -------------------------------------------------------------------------- */

function winnerName(award: Award) {
  return award.winner.profile?.username || award.winner.name;
}

/* -------------------------------------------------------------------------- */
/*                           STATIC Background - NO ANIMATIONS               */
/* -------------------------------------------------------------------------- */

const DecorBackground = memo(() => {
  const isMobile = useIsMobile();
  
  if (isMobile) {
    return (
      <div className="pointer-events-none fixed inset-0 -z-10 bg-gradient-to-br from-gray-900 via-gray-900 to-indigo-950" />
    );
  }

  return (
    <div className="pointer-events-none fixed inset-0 -z-10 overflow-hidden bg-gradient-to-br from-gray-900 via-gray-900 to-indigo-950">
      <div className="absolute -left-32 top-0 h-96 w-96 rounded-full bg-yellow-500/20 blur-3xl" />
      <div className="absolute right-0 top-1/3 h-96 w-96 rounded-full bg-amber-500/15 blur-3xl" />
      <div className="absolute bottom-0 left-1/3 h-96 w-96 rounded-full bg-purple-600/15 blur-3xl" />
      <div
        className="absolute inset-0 opacity-[0.15]"
        style={{
          backgroundImage:
            "linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)",
          backgroundSize: "48px 48px",
        }}
      />
    </div>
  );
});

DecorBackground.displayName = "DecorBackground";

/* -------------------------------------------------------------------------- */
/*                           Memoized Components                             */
/* -------------------------------------------------------------------------- */

// === STATIC Stat Card ===
const StatCard = memo(({ stat }: { stat: any }) => {
  const Icon = stat.icon;
  return (
    <div className={`group relative h-full overflow-hidden rounded-2xl border bg-white/5 p-4 shadow-xl backdrop-blur-xl transition-colors duration-150 hover:border-yellow-500/40 ${stat.ring}`}>
      <div className={`pointer-events-none absolute -right-6 -top-6 h-20 w-20 rounded-full bg-gradient-to-br ${stat.glow} to-transparent opacity-40 blur-2xl transition-opacity duration-300 group-hover:opacity-70`} />
      <div className="relative flex items-center justify-between gap-2">
        <div className="min-w-0">
          <p className={`text-2xl font-bold ${stat.accent}`}>{stat.value}</p>
          <p className="mt-0.5 truncate text-xs text-gray-400 sm:text-sm">{stat.label}</p>
        </div>
        <span className={`flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-xl bg-white/5 ${stat.accent}`}>
          <Icon className="h-5 w-5" />
        </span>
      </div>
      <p className="relative mt-2 truncate text-[11px] text-gray-500">{stat.hint}</p>
    </div>
  );
});

StatCard.displayName = "StatCard";

// === STATIC Award Card ===
const AwardCard = memo(({ award, onDelete }: { award: Award; onDelete: (id: string) => void }) => {
  const Icon = iconMap[award.icon] || <Award className="h-5 w-5 text-gray-400" />;
  const name = winnerName(award);
  const handleDelete = useCallback(() => {
    onDelete(award.id);
  }, [onDelete, award.id]);

  return (
    <div className="group relative overflow-hidden rounded-2xl border border-white/10 bg-white/5 p-4 shadow-xl backdrop-blur-xl transition-colors duration-150 hover:border-yellow-500/40 sm:p-5">
      <div className="pointer-events-none absolute -right-12 -top-12 h-28 w-28 rounded-full bg-yellow-500/10 blur-3xl transition-opacity duration-300 group-hover:opacity-100" />
      <div className="relative flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-4">
          <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-2xl border border-white/10 bg-gray-900/60 shadow-lg">
            {Icon}
          </div>
          <div className="min-w-0">
            <div className="mb-2 flex flex-wrap items-center gap-2">
              <h2 className="min-w-0 truncate text-lg font-semibold text-white">{award.name}</h2>
              <span className="rounded-full border border-white/10 bg-gray-900/50 px-2.5 py-1 text-xs text-gray-300">
                {award.category}
              </span>
              {award.isAutoGenerated && (
                <span className="inline-flex items-center gap-1 rounded-full border border-green-400/20 bg-green-500/15 px-2.5 py-1 text-xs font-medium text-green-300">
                  <Bot className="h-3 w-3" />
                  Auto
                </span>
              )}
            </div>

            <div className="grid gap-2 text-sm text-gray-400 sm:grid-cols-2">
              <span className="flex min-w-0 items-center gap-2 rounded-xl bg-gray-900/40 px-3 py-2">
                <Crown size={14} className="flex-shrink-0 text-yellow-400" />
                Winner: <b className="truncate text-white">{name}</b>
              </span>
              <span className="flex min-w-0 items-center gap-2 rounded-xl bg-gray-900/40 px-3 py-2">
                <Trophy size={14} className="flex-shrink-0 text-amber-400" />
                Season: <b className="truncate text-white">{award.season.name}</b>
              </span>
              <span className="flex min-w-0 items-center gap-2 rounded-xl bg-gray-900/40 px-3 py-2 sm:col-span-2">
                <Calendar size={14} className="flex-shrink-0 text-blue-400" />
                Awarded: {new Date(award.awardedAt).toLocaleDateString()}
              </span>
            </div>

            {award.description && (
              <p className="mt-3 line-clamp-2 text-sm text-gray-400">{award.description}</p>
            )}
          </div>
        </div>

        <button
          onClick={handleDelete}
          className="flex min-h-[44px] min-w-[44px] items-center justify-center rounded-xl border border-red-400/20 bg-red-500/10 text-red-300 transition-colors duration-150 hover:bg-red-500/20 sm:flex-shrink-0"
          title="Delete award"
        >
          <Trash2 size={18} />
        </button>
      </div>
    </div>
  );
});

AwardCard.displayName = "AwardCard";

/* -------------------------------------------------------------------------- */
/*                               Main Component                               */
/* -------------------------------------------------------------------------- */

export default function AdminAwardsPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const isMobile = useIsMobile();
  const [awards, setAwards] = useState<Award[]>([]);
  const [seasons, setSeasons] = useState<Season[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedSeason, setSelectedSeason] = useState<string>("all");
  const [generating, setGenerating] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const [deletingId, setDeletingId] = useState<string | null>(null);

  useEffect(() => {
    if (status === "loading") return;
    if (!session) {
      router.push("/auth/signin");
      return;
    }
    if (session.user?.role !== "ADMIN") {
      router.push("/dashboard");
      return;
    }
  }, [session, status, router]);

  useEffect(() => {
    if (session?.user?.role === "ADMIN") {
      fetchData();
    }
  }, [session]);

  async function fetchData() {
    await Promise.all([fetchSeasons(), fetchAwards()]);
    setLoading(false);
  }

  async function fetchSeasons() {
    const res = await fetch("/api/seasons");
    const data = await res.json();
    setSeasons(Array.isArray(data) ? data : []);
  }

  async function fetchAwards() {
    const res = await fetch("/api/awards");
    const data = await res.json();
    setAwards(Array.isArray(data) ? data : []);
  }

  const generateAwards = useCallback(async () => {
    if (!selectedSeason || selectedSeason === "all") {
      toast.error("Please select a specific season");
      return;
    }

    setGenerating(true);

    const res = await fetch("/api/admin/awards/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ seasonId: selectedSeason }),
    });

    const data = await res.json();

    if (res.ok) {
      toast.success(data.message || "Awards generated successfully!");
      fetchAwards();
    } else {
      toast.error(data.error || "Failed to generate awards");
    }

    setGenerating(false);
  }, [selectedSeason]);

  const deleteAward = useCallback(async (id: string) => {
    if (!confirm("Are you sure you want to delete this award?")) return;

    setDeletingId(id);
    try {
      const res = await fetch(`/api/awards/${id}`, { method: "DELETE" });
      if (res.ok) {
        toast.success("Award deleted");
        fetchAwards();
      } else {
        toast.error("Failed to delete");
      }
    } catch (error) {
      toast.error("Failed to delete");
    } finally {
      setDeletingId(null);
    }
  }, []);

  const regenerateAwards = useCallback(async () => {
    if (!selectedSeason || selectedSeason === "all") {
      toast.error("Please select a specific season");
      return;
    }

    if (!confirm("This will delete all existing awards for this season and regenerate them. Continue?")) return;

    setGenerating(true);

    await fetch("/api/admin/awards/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        seasonId: selectedSeason,
        action: "delete",
      }),
    });

    const res = await fetch("/api/admin/awards/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ seasonId: selectedSeason }),
    });

    const data = await res.json();

    if (res.ok) {
      toast.success(data.message || "Awards regenerated successfully!");
      fetchAwards();
    } else {
      toast.error(data.error || "Failed to regenerate awards");
    }

    setGenerating(false);
  }, [selectedSeason]);

  const filteredAwards = useMemo(() => {
    const bySeason =
      selectedSeason === "all"
        ? awards
        : awards.filter((a) => a.season.id === selectedSeason);

    if (!searchTerm.trim()) return bySeason;

    const query = searchTerm.toLowerCase();
    return bySeason.filter((award) =>
      [award.name, award.category, award.description, winnerName(award), award.season.name]
        .join(" ")
        .toLowerCase()
        .includes(query)
    );
  }, [awards, searchTerm, selectedSeason]);

  const selectedSeasonName = useMemo(() =>
    selectedSeason === "all"
      ? "All Seasons"
      : seasons.find((season) => season.id === selectedSeason)?.name || "Selected Season",
    [selectedSeason, seasons]
  );

  const autoCount = useMemo(() => awards.filter((a) => a.isAutoGenerated).length, [awards]);
  const manualCount = useMemo(() => awards.filter((a) => !a.isAutoGenerated).length, [awards]);
  const uniqueWinners = useMemo(() => new Set(awards.map((a) => winnerName(a))).size, [awards]);

  const statCards = useMemo(() => [
    {
      label: "Total Awards",
      value: awards.length,
      hint: "All trophies issued",
      icon: Award,
      accent: "text-yellow-400",
      ring: "border-yellow-500/20",
      glow: "from-yellow-500/20",
    },
    {
      label: "Auto-Generated",
      value: autoCount,
      hint: "System calculated",
      icon: Bot,
      accent: "text-green-400",
      ring: "border-green-500/20",
      glow: "from-green-500/20",
    },
    {
      label: "Manual",
      value: manualCount,
      hint: "Admin-created awards",
      icon: UserRound,
      accent: "text-blue-400",
      ring: "border-blue-500/20",
      glow: "from-blue-500/20",
    },
    {
      label: "Winners",
      value: uniqueWinners,
      hint: "Unique award winners",
      icon: Medal,
      accent: "text-purple-400",
      ring: "border-purple-500/20",
      glow: "from-purple-500/20",
    },
  ], [awards, autoCount, manualCount, uniqueWinners]);

  const handleSearchChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchTerm(e.target.value);
  }, []);

  const handleSeasonChange = useCallback((e: React.ChangeEvent<HTMLSelectElement>) => {
    setSelectedSeason(e.target.value);
  }, []);

  if (status === "loading" || loading) {
    return (
      <>
        <DecorBackground />
        <div className="flex h-64 items-center justify-center px-4">
          <div className="text-center">
            <div className="relative mx-auto mb-4 h-16 w-16">
              <div className="absolute inset-0 rounded-full border-4 border-yellow-500/20" />
              <div className="absolute inset-0 animate-spin rounded-full border-4 border-yellow-500 border-t-transparent" />
              <Award className="absolute inset-0 m-auto h-6 w-6 text-yellow-400" />
            </div>
            <p className="mt-2 font-medium text-gray-400">Loading awards...</p>
            <div className="mt-1 flex items-center justify-center gap-1 text-xs text-gray-500">
              <Sparkles className="h-3 w-3 text-yellow-400" />
              <span>Fetching trophies</span>
            </div>
          </div>
        </div>
      </>
    );
  }

  if (session?.user?.role !== "ADMIN") {
    return null;
  }

  return (
    <>
      <DecorBackground />
      <div className="space-y-4 px-3 pb-20 sm:space-y-6 sm:px-4 lg:px-6">
        {/* Header - NO animations */}
        <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-r from-yellow-600/20 via-amber-600/20 to-purple-600/20 p-4 shadow-2xl backdrop-blur-xl sm:p-6">
          <div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-yellow-500/20 blur-3xl" />
          <div className="relative flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div className="flex min-w-0 items-center gap-3">
              <span className="flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-yellow-500 to-amber-600 shadow-lg shadow-yellow-500/30 sm:h-12 sm:w-12">
                <Award className="h-5 w-5 text-white sm:h-6 sm:w-6" />
              </span>
              <div className="min-w-0">
                <h1 className="truncate text-xl font-bold text-white sm:text-2xl">
                  🏅 Awards Management
                </h1>
                <p className="mt-0.5 truncate text-xs text-gray-300 sm:text-sm">
                  Manage awards and trophies for each season
                </p>
              </div>
            </div>
            <span className="flex w-fit items-center gap-1.5 rounded-xl border border-yellow-400/30 bg-yellow-500/10 px-3 py-2 text-xs font-semibold text-yellow-300">
              <Sparkles className="h-3.5 w-3.5" />
              {selectedSeasonName}
            </span>
          </div>
        </div>

        {/* Controls - NO animations */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-4 shadow-2xl backdrop-blur-xl sm:p-6">
          <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
            <div className="grid gap-3 sm:grid-cols-2">
              <div>
                <label className="mb-1 block text-sm font-medium text-gray-300">Select Season</label>
                <div className="relative">
                  <Filter className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-500" />
                  <select
                    value={selectedSeason}
                    onChange={handleSeasonChange}
                    className="min-h-[44px] w-full appearance-none rounded-xl border border-white/10 bg-gray-900/50 py-2 pl-10 pr-4 text-white transition-colors duration-150 focus:border-yellow-500 focus:outline-none focus:ring-2 focus:ring-yellow-500/30"
                  >
                    <option value="all">All Seasons</option>
                    {seasons.map((s) => (
                      <option key={s.id} value={s.id}>
                        {s.name} {s.isActive ? "(Active)" : ""}
                      </option>
                    ))}
                  </select>
                </div>
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium text-gray-300">Search Awards</label>
                <div className="relative">
                  <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-500" />
                  <input
                    value={searchTerm}
                    onChange={handleSearchChange}
                    placeholder="Search award, winner, season..."
                    className="min-h-[44px] w-full rounded-xl border border-white/10 bg-gray-900/50 py-2 pl-10 pr-4 text-white placeholder-gray-500 transition-colors duration-150 focus:border-yellow-500 focus:outline-none focus:ring-2 focus:ring-yellow-500/30"
                  />
                </div>
              </div>
            </div>

            <div className="flex flex-col gap-2 sm:flex-row">
              <button
                onClick={generateAwards}
                disabled={generating || selectedSeason === "all"}
                className="flex min-h-[44px] items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-green-600 to-emerald-600 px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-green-900/30 transition-all duration-150 hover:from-green-700 hover:to-emerald-700 disabled:opacity-50"
              >
                {generating ? (
                  <Loader2 size={16} className="animate-spin" />
                ) : (
                  <RefreshCw size={16} />
                )}
                {generating ? "Generating..." : "Generate Awards"}
              </button>
              {selectedSeason !== "all" && filteredAwards.length > 0 && (
                <button
                  onClick={regenerateAwards}
                  disabled={generating}
                  className="flex min-h-[44px] items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-yellow-600 to-amber-600 px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-yellow-900/30 transition-all duration-150 hover:from-yellow-700 hover:to-amber-700 disabled:opacity-50"
                >
                  <Wand2 size={16} />
                  Regenerate
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Stats - NO animations */}
        <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
          {statCards.map((stat) => (
            <StatCard key={stat.label} stat={stat} />
          ))}
        </div>

        {/* Awards - NO animations */}
        {filteredAwards.length === 0 ? (
          <div className="rounded-2xl border border-white/10 bg-white/5 py-12 text-center shadow-2xl backdrop-blur-xl">
            <Award className="mx-auto mb-4 h-16 w-16 text-gray-600" />
            <h3 className="mb-2 text-xl font-semibold text-white">No Awards Yet</h3>
            <p className="px-4 text-gray-400">
              {searchTerm
                ? "No awards match your search."
                : "Select a season and click Generate Awards to create them automatically."}
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
            {filteredAwards.map((award) => (
              <AwardCard
                key={award.id}
                award={award}
                onDelete={deleteAward}
              />
            ))}
          </div>
        )}
      </div>
    </>
  );
}